name: fenicstorch_j
prefix: /Home/optimier/schuette/anaconda3/envs/fenicstorchcosi
channels:
  # - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=heab0d09_28
  - blas=1.0=mkl
  - boost-cpp=1.70.0=h7b93d67_3
  - brotli-python=1.0.9=py38h709712a_5
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cmake=3.18.2=h5c55442_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - eigen=3.3.7=hc9558a2_1001
  - expat=2.2.9=he1b5a44_2
  - fastcache=1.1.0=py38h1e0a361_1
  - fenics-dijitso=2019.1.0=py_10
  - fenics-dolfin=2019.1.0=py38ha98eaef_8
  - fenics-ffc=2019.1.0=py_10
  - fenics-fiat=2019.1.0=py_10
  - fenics-libdolfin=2019.1.0=hce00427_8
  - fenics-ufl=2019.1.0=py_10
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - freetype=2.10.2=he06d7ca_0
  - gcc_impl_linux-64=7.5.0=hdb87b24_16
  - gcc_linux-64=7.5.0=hf34d7eb_28
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.0=he1b5a44_2
  - gmpy2=2.1.0b1=py38h04dde30_0
  - gnutls=3.6.13=h85f3911_1
  - gxx_impl_linux-64=7.5.0=h1104b78_16
  - gxx_linux-64=7.5.0=ha781d05_28
  - hdf5=1.10.5=mpi_mpich_ha7d0aea_1004
  - hypre=2.18.2=hc98498a_1
  - icu=67.1=he1b5a44_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h516909a_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=hfafb76e_3
  - lame=3.100=h7f98852_1001
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=21_mkl
  - libcblas=3.8.0=21_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=7.71.1=hcdd3856_6
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=7.5.0=h42c25f5_16
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - libjpeg-turbo=2.1.0=h7f98852_0
  - liblapack=3.8.0=21_mkl
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=7.5.0=h4084dd6_16
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuv=1.39.0=h516909a_0
  - libwebp=1.1.0=h76fa15c_4
  - libwebp-base=1.1.0=h516909a_3
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h91b0d89_0
  - metis=5.1.0=he1b5a44_1006
  - mkl=2020.2=256
  - mpc=1.1.0=h04dde30_1009
  - mpfr=4.0.2=he80fd80_1
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py38h4a80816_1
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.1.0=py_0
  - mshr=2019.1.0=py38h255090a_2
  - mumps-include=5.2.1=6
  - mumps-mpi=5.2.1=h645f208_6
  - ncurses=6.2=he1b5a44_1
  - nettle=3.6=he412f7d_0
  - networkx=2.5=py_0
  - olefile=0.46=py_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - parmetis=4.0.3=h9f7b9cf_1005
  - petsc=3.12.4=h432f2ec_0
  - petsc4py=3.12.0=py38h30bdb2a_4
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.3=py_0
  - pkg-config=0.29.2=h516909a_1006
  - pkgconfig=1.4.0=py38h32f6830_0
  - ptscotch=6.0.8=he9f2703_1
  - pybind11=2.4.3=py38hbf85e49_3
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.5=h1103e12_8_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=2.4.1=py3.8_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - readline=8.0=he28a2e2_2
  - rhash=1.3.6=h14c3975_1001
  - scalapack=2.0.2=hfacbc1e_1008
  - scipy=1.5.2=py38h8c5af15_0
  - scotch=6.0.8=h0eec0ba_1
  - setuptools=49.6.0=py38h32f6830_1
  - six=1.15.0=pyh9f0ad1d_0
  - slepc=3.12.2=h76dbdef_0
  - slepc4py=3.12.0=py38hb2ee469_1
  - sqlite=3.33.0=h4cf870e_0
  - suitesparse=5.6.0=h717dc36_0
  - superlu=5.2.1=hfe2efc7_1207
  - superlu_dist=6.2.0=h5e15a89_2
  - sympy=1.6.2=py38h32f6830_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tbb=2020.2=hc9558a2_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_0
  - torchaudio=2.4.1=py38_cu118
  - torchtriton=3.0.0=py38
  - tornado=6.0.4=py38h1e0a361_1
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
      - absl-py==0.11.0
      - cachetools==4.1.1
      - chardet==3.0.4
      - dgl==0.5.3
      - fsspec==0.8.4
      - future==0.18.2
      - google-auth==1.23.0
      - google-auth-oauthlib==0.4.2
      - grpcio==1.33.2
      - idna==2.10
      - markdown==3.3.3
      - numpy==1.24.4
      - oauthlib==3.1.0
      - packaging==20.4
      - protobuf==3.13.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pytorch-lightning==0.7.1
      - pyyaml==5.3.1
      - requests==2.24.0
      - requests-oauthlib==1.3.0
      - rsa==4.6
      - tensorboard==2.2.0
      - tensorboard-plugin-wit==1.7.0
      - torch==1.6.0
      - torchvision==0.7.0
      - tqdm==4.51.0
      - urllib3==1.25.11
      - werkzeug==1.0.1
      - intel-openmp=2022.0.1=h06a4308_3633 #
      - scikit-learn=0.23.2=py38h0573a6f_0 #
# prefix: /home/wias/.conda/envs/fenicstorch
